### ISSUE TITLE
Open Schematic, get "The following libraries were not found:  *special  *xess"

### ISSUE THREAD

**Issue by johnrbnsn** [xesscorp/RPi_Hat_Template#3]
I just installed your RPi Hat Template, and every time I try to open the schematic I get an error, "

The following libraries were not found:
- special
- xess

I installed your .pretty files for this board, and your main KiCad repo.  Any ideas?

**Comment by seandepagnier** [comment]
I also find this error.

**Comment by msandres13** [comment]
I get the same error

**Comment by xesscorp** [comment]
The RPi template is pretty old. KiCad renamed the `special` library to `device`. That's probably the cause of this error.

**Comment by johnrbnsn** [comment]
Do you have suggestions on a newer template, or plans on updating this one?

**Comment by xesscorp** [comment]
I wouldn't be surprised if the KiCad libraries now had an official RPi Hat template. There is another 3rd-party template [here](https://github.com/jonbuford/kicad-library/tree/RPi_HAT/template/raspberrrypi_hat).

I removed the `special` and `xess` libraries from the template since they were not needed. This template may work for you now.
